version: '3.7'

services:
  sigal:
    build: build
    volumes:
      - ./run/data/sigal-srv_pictures:/srv/pictures:ro
      - ./run/data/sigal-srv__build:/srv/_build:rw
      - ./run/scripts/action.sh:/sbin/action.sh:ro
    env_file: .env
    command: "inotifyd action.sh /srv/pictures:ymnd"

  web:
    image: httpd
    #restart: on-failure:3
    read_only: true
    volumes:
      - ./run/data/sigal-srv__build:/usr/local/apache2/htdocs:ro
      - web-usr_local_apache2_logs:/usr/local/apache2/logs:rw
    expose:
      - "80"
    env_file: .env
    networks:
      - br-internet
    healthcheck:
      test: bash -c ">/dev/tcp/127.0.0.1/80"

volumes:
   web-usr_local_apache2_logs:
     driver: local

networks:
  br-internet:
    external:
      name: nginx-proxy

